CREATE TABLE users(
	username VARCHAR(20) NOT NULL,
	firstname VARCHAR(20) NOT NULL, 
	lastname VARCHAR(20) NOT NULL, 
	email VARCHAR(40) NOT NULL, 
	filename VARCHAR(64) NOT NULL, 
	password VARCHAR(256) NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY(username)
);

CREATE TABLE general(
	user VARCHAR(20) NOT NULL PRIMARY KEY, 
	age INT NOT NULL,
	sex VARCHAR(20) NOT NULL,
	weight INT NOT NULL,
	height INT NOT NULL,
	race VARCHAR(20) NOT NULL,
	FOREIGN KEY (user) REFERENCES users(username)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);
